### ISSUE TITLE
remove googleservices.json file from project

### ISSUE THREAD

**Issue by droidbaker** [droidbaker/TicTacToe-Online#4]

**Comment by radiantly** [comment]
I can do this! Just need to remove that one file, right?

**Comment by droidbaker** [comment]
No just add a section in readme on how to connect the project with firebase. Remember to do it in a seperate branch. @radiantly

**Comment by bit-man** [comment]
@radiantly Here's an example from a [similar issue](https://github.com/shivamkumard107/FirebaseMLKit/pull/6/commits/d23d62a3c4eec021f62d56e3659974cadbfbba12)

**Comment by droidbaker** [comment]
Issue resolved by @gaurav-ag10
